esphome:
  name: midea-dehumidifier

esp8266:
  board: esp01_1m

external_components:
  - source:
      type: git
      url: https://github.com/Chreece/ESPHome-Dehumidifier
      ref: main
    components: [midea_dehum]
    refresh: 0min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
logger:
  baud_rate: 0
  hardware_uart: UART0_SWAP

api:
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: !secret ota_update

uart:
  id: uart_midea
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 256

midea_dehum:
  id: midea_dehum_comp
  uart_id: uart_midea

climate:
  - platform: midea_dehum
    midea_dehum_id: midea_dehum_comp
    name: "Inventor Dehumidifier"

binary_sensor:
  - platform: midea_dehum
    midea_dehum_id: midea_dehum_comp
    bucket_full:
      name: "Bucket Full"

#optional sensor
sensor:
  - platform: midea_dehum
    midea_dehum_id: midea_dehum_comp
    error:
      name: "Error Code"

#optional switch if your device has ionizer
switch:
  - platform: midea_dehum
    midea_dehum_id: midea_dehum_comp
    ionizer:
      name: "Ionizer"