esphome:
  name: midea-dehumidifier

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/Chreece/ESPHome-Dehumidifier
      ref: main
    components: [midea_dehum]

uart:
  id: uart_midea
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600

midea_dehum:
  id: midea_dehum_comp
  uart_id: uart_midea

  # 🆕 Optional: Rename display modes to match your device’s front panel
  # Some units show LEDs or labels like “Cont”, “Dry”, “Smart”, etc.
  # The logic protocol remains unchanged — only the names in Home Assistant are updated.
  display_mode_setpoint: 'Unused'
  display_mode_continuous: 'Cont'
  display_mode_smart: 'Smart'
  display_mode_clothes_drying: 'Dry'

climate:
  - platform: midea_dehum
    midea_dehum_id: midea_dehum_comp
    name: "Inventor Dehumidifier"

binary_sensor:
  - platform: midea_dehum
    midea_dehum_id: midea_dehum_comp
    bucket_full:
      name: "Bucket Full"

# Optional error sensor remove this block if not needed
sensor:
  - platform: midea_dehum
    midea_dehum_id: midea_dehum_comp
    error:
      name: "Error Code"

# Optional ionizer control, add this block only if your device has Ionizer
switch:
  - platform: midea_dehum
    midea_dehum_id: midea_dehum_comp
    ionizer:
      name: "Ionizer"
