esphome:
  name: midea-dehumidifier

esp8266:
  board: esp01_1m

external_components:
  - source:
      type: git
      url: https://github.com/Chreece/ESPHome-Dehumidifier
      ref: main
    components: [midea_dehum]
    refresh: 0min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: !secret ota_update

uart:
  id: dehum_uart
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  rx_buffer_size: 256

midea_dehum:
  id: midea_dehum_comp
  uart_id: dehum_uart
  error:
    name: "Dehumidifier Error"

climate:
sensor:
