esphome:
  name: midea_dehumidifier

esp8266:
  board: esp01_1m

external_components:
  - source:
      type: git
      url: https://github.com/Chreece/Esphome-Dehumidifier
      ref: main
    refresh: 3h
    components: [midea_dehum]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "MideaDehum Fallback"
    password: !secret fallback_pass

logger:
  baud_rate: 0  # disable logging over UART

ota:
  - platform: esphome
    password: !secret ota_update

api:
  encryption:
    key: !secret encryption_key
    
uart:
  id: dehum_uart
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  rx_buffer_size: 256

midea_dehum:
  id: midea_dehum_comp
  uart_id: dehum_uart